# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora/25-cloud-base"
    fedora.vm.provision :shell, path: "fedora_bootstrap.sh"
    fedora.vm.provider :libvirt do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 16
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.provision :shell, path: "centos_bootstrap.sh"
    centos.vm.provider :libvirt do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 16
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "elastic/ubuntu-14.04-x86_64"
    ubuntu.vm.provision :shell, path: "ubuntu_bootstrap.sh"
    ubuntu.vm.provider :libvirt do |libvirt|
      libvirt.memory = 4096
      libvirt.cpus = 4
    end
  end

end
