#!/bin/bash

set -x

TOOLCHAINCMD="$1"
shift

if [[ -z "$KPATCH_GCC_TEMPDIR" ]]; then
	# RHEL6: FIXME: -ffunction-sections and -pg are incompatible w/ ea. other
	# When used together, -ffunction-sections gets dropped.
	# Drop -pg for now...
	# Also, ${var%-pg} breaks exec cmd, so sub with bogus option for now..
	exec "$TOOLCHAINCMD" "${@/%-pg/-Wno-error=comment}"
fi

declare -a args=("$@")

if [[ "$TOOLCHAINCMD" = "gcc" ]] ; then
	while [ "$#" -gt 0 ]; do
		if [ "$1" = "-o" ]; then
			obj=$2
			[[ ! $2 = */.tmp_mc_*.o ]] && [[ $2 = */.tmp_*.o ]] && obj=${2/.tmp_/}
			# RHEL6: FIXME: Figure out .tmp_mc_*.o
			case "$obj" in
				*.mod.o|\
				*built-in.o|\
				vmlinux.o|\
				.tmp_kallsyms1.o|\
				.tmp_kallsyms2.o|\
				init/version.o|\
				arch/x86/boot/version.o|\
				arch/x86/boot/compressed/eboot.o|\
				arch/x86/boot/header.o|\
				arch/x86/boot/compressed/efi_stub_64.o|\
				arch/x86/boot/compressed/piggy.o|\
				kernel/system_certificates.o|\
				arch/x86/vdso/*|\
				arch/x86/entry/vdso/*|\
				drivers/firmware/efi/libstub/*|\
				*.tmp_mc*.o|\
				.*.o)
					break
					;;
				*.o)
					mkdir -p "$KPATCH_GCC_TEMPDIR/orig/$(dirname $obj)"
					[[ -e $obj ]] && cp -f "$obj" "$KPATCH_GCC_TEMPDIR/orig/$obj"
					echo "$obj" >> "$KPATCH_GCC_TEMPDIR/changed_objs"
					break
					;;
				*)
					break
					;;
			esac
		fi
		shift
	done
elif [[ "$TOOLCHAINCMD" = "ld" ]] ; then
	while [ "$#" -gt 0 ]; do
		if [ "$1" = "-o" ]; then
			obj=$2
			case "$obj" in
				# RHEL6: FIXME: Modules are linked to .ko.unsigned file first..
				*.ko.unsigned)
					mkdir -p "$KPATCH_GCC_TEMPDIR/module/$(dirname $obj)"
					cp -f "$obj" "$KPATCH_GCC_TEMPDIR/module/$obj"
					break
					;;
				.tmp_vmlinux*|vmlinux)
					args+=(--warn-unresolved-symbols)
					break
					;;
				*)
					break
					;;
			esac
		fi
		shift
	done
fi

exec "$TOOLCHAINCMD" "${args[@]/%-pg/-Wno-error=comment}"
