#!/bin/bash

# LC_COLLATE=C to mimic kernel build (for sorting)
export LC_COLLATE=C

BUILD_DIR="$1"

echo "klp-convert-symbol-data.0.1"
echo "*vmlinux"
nm -f posix "$BUILD_DIR"/vmlinux | cut -d\  -f1

while IFS= read -r o; do

    # Skip livepatch modules
    modinfo --field livepatch "$BUILD_DIR/${o}.ko" | grep -q '^Y$' && continue

    echo "*$(basename -s .ko "$o")"
    nm -f posix "$BUILD_DIR/${o}.o" | cut -d\  -f1

done < <(sort -u $BUILD_DIR/modules.order | sed -e 's/^kernel\///' -e 's/\.ko$//')
# TODO: why do older kernels prefix "kernel/" to modules.order entries?
